/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/light_energy_menagment_system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(light_energy_menagment_system_Device, light_energy_menagment_system_Device, AUTO)


PB_BIND(light_energy_menagment_system_LampData, light_energy_menagment_system_LampData, AUTO)


PB_BIND(light_energy_menagment_system_DataPacket, light_energy_menagment_system_DataPacket, AUTO)



