/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "proto/light_energy_management_system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(light_energy_management_system_Device, light_energy_management_system_Device, AUTO)


PB_BIND(light_energy_management_system_Measurement, light_energy_management_system_Measurement, AUTO)


PB_BIND(light_energy_management_system_DeviceMeasurments, light_energy_management_system_DeviceMeasurments, AUTO)


PB_BIND(light_energy_management_system_DataPacket, light_energy_management_system_DataPacket, AUTO)





