// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lamp_controller.proto

#include "lamp_controller.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace lamp_controller {
class LampDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LampData>
      _instance;
} _LampData_default_instance_;
}  // namespace lamp_controller
namespace protobuf_lamp_5fcontroller_2eproto {
static void InitDefaultsLampData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::lamp_controller::_LampData_default_instance_;
    new (ptr) ::lamp_controller::LampData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::lamp_controller::LampData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LampData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLampData}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_LampData.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, illuminance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, voltage_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, current_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, power_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, energy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, frequency_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lamp_controller::LampData, power_factor_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::lamp_controller::LampData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::lamp_controller::_LampData_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "lamp_controller.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025lamp_controller.proto\022\017lamp_controller"
      "\"\227\001\n\010LampData\022\014\n\004name\030\001 \001(\t\022\023\n\013illuminan"
      "ce\030\002 \001(\002\022\017\n\007voltage\030\003 \001(\002\022\017\n\007current\030\004 \001"
      "(\002\022\r\n\005power\030\005 \001(\002\022\016\n\006energy\030\006 \001(\002\022\021\n\tfre"
      "quency\030\007 \001(\002\022\024\n\014power_factor\030\010 \001(\002b\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 202);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lamp_controller.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_lamp_5fcontroller_2eproto
namespace lamp_controller {

// ===================================================================

void LampData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LampData::kNameFieldNumber;
const int LampData::kIlluminanceFieldNumber;
const int LampData::kVoltageFieldNumber;
const int LampData::kCurrentFieldNumber;
const int LampData::kPowerFieldNumber;
const int LampData::kEnergyFieldNumber;
const int LampData::kFrequencyFieldNumber;
const int LampData::kPowerFactorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LampData::LampData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_lamp_5fcontroller_2eproto::scc_info_LampData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:lamp_controller.LampData)
}
LampData::LampData(const LampData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&illuminance_, &from.illuminance_,
    static_cast<size_t>(reinterpret_cast<char*>(&power_factor_) -
    reinterpret_cast<char*>(&illuminance_)) + sizeof(power_factor_));
  // @@protoc_insertion_point(copy_constructor:lamp_controller.LampData)
}

void LampData::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&illuminance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&power_factor_) -
      reinterpret_cast<char*>(&illuminance_)) + sizeof(power_factor_));
}

LampData::~LampData() {
  // @@protoc_insertion_point(destructor:lamp_controller.LampData)
  SharedDtor();
}

void LampData::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LampData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LampData::descriptor() {
  ::protobuf_lamp_5fcontroller_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lamp_5fcontroller_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LampData& LampData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_lamp_5fcontroller_2eproto::scc_info_LampData.base);
  return *internal_default_instance();
}


void LampData::Clear() {
// @@protoc_insertion_point(message_clear_start:lamp_controller.LampData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&illuminance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&power_factor_) -
      reinterpret_cast<char*>(&illuminance_)) + sizeof(power_factor_));
  _internal_metadata_.Clear();
}

bool LampData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:lamp_controller.LampData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "lamp_controller.LampData.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float illuminance = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &illuminance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float voltage = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &voltage_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float current = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &current_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float power = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &power_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float energy = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &energy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float frequency = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(61u /* 61 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &frequency_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float power_factor = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(69u /* 69 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &power_factor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:lamp_controller.LampData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:lamp_controller.LampData)
  return false;
#undef DO_
}

void LampData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:lamp_controller.LampData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lamp_controller.LampData.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // float illuminance = 2;
  if (this->illuminance() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->illuminance(), output);
  }

  // float voltage = 3;
  if (this->voltage() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->voltage(), output);
  }

  // float current = 4;
  if (this->current() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->current(), output);
  }

  // float power = 5;
  if (this->power() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->power(), output);
  }

  // float energy = 6;
  if (this->energy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->energy(), output);
  }

  // float frequency = 7;
  if (this->frequency() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->frequency(), output);
  }

  // float power_factor = 8;
  if (this->power_factor() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->power_factor(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:lamp_controller.LampData)
}

::google::protobuf::uint8* LampData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:lamp_controller.LampData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lamp_controller.LampData.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // float illuminance = 2;
  if (this->illuminance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->illuminance(), target);
  }

  // float voltage = 3;
  if (this->voltage() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->voltage(), target);
  }

  // float current = 4;
  if (this->current() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->current(), target);
  }

  // float power = 5;
  if (this->power() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->power(), target);
  }

  // float energy = 6;
  if (this->energy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->energy(), target);
  }

  // float frequency = 7;
  if (this->frequency() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->frequency(), target);
  }

  // float power_factor = 8;
  if (this->power_factor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->power_factor(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lamp_controller.LampData)
  return target;
}

size_t LampData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lamp_controller.LampData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // float illuminance = 2;
  if (this->illuminance() != 0) {
    total_size += 1 + 4;
  }

  // float voltage = 3;
  if (this->voltage() != 0) {
    total_size += 1 + 4;
  }

  // float current = 4;
  if (this->current() != 0) {
    total_size += 1 + 4;
  }

  // float power = 5;
  if (this->power() != 0) {
    total_size += 1 + 4;
  }

  // float energy = 6;
  if (this->energy() != 0) {
    total_size += 1 + 4;
  }

  // float frequency = 7;
  if (this->frequency() != 0) {
    total_size += 1 + 4;
  }

  // float power_factor = 8;
  if (this->power_factor() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LampData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:lamp_controller.LampData)
  GOOGLE_DCHECK_NE(&from, this);
  const LampData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LampData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:lamp_controller.LampData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:lamp_controller.LampData)
    MergeFrom(*source);
  }
}

void LampData::MergeFrom(const LampData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:lamp_controller.LampData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.illuminance() != 0) {
    set_illuminance(from.illuminance());
  }
  if (from.voltage() != 0) {
    set_voltage(from.voltage());
  }
  if (from.current() != 0) {
    set_current(from.current());
  }
  if (from.power() != 0) {
    set_power(from.power());
  }
  if (from.energy() != 0) {
    set_energy(from.energy());
  }
  if (from.frequency() != 0) {
    set_frequency(from.frequency());
  }
  if (from.power_factor() != 0) {
    set_power_factor(from.power_factor());
  }
}

void LampData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:lamp_controller.LampData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LampData::CopyFrom(const LampData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lamp_controller.LampData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LampData::IsInitialized() const {
  return true;
}

void LampData::Swap(LampData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LampData::InternalSwap(LampData* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(illuminance_, other->illuminance_);
  swap(voltage_, other->voltage_);
  swap(current_, other->current_);
  swap(power_, other->power_);
  swap(energy_, other->energy_);
  swap(frequency_, other->frequency_);
  swap(power_factor_, other->power_factor_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LampData::GetMetadata() const {
  protobuf_lamp_5fcontroller_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lamp_5fcontroller_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace lamp_controller
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::lamp_controller::LampData* Arena::CreateMaybeMessage< ::lamp_controller::LampData >(Arena* arena) {
  return Arena::CreateInternal< ::lamp_controller::LampData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
