/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_LIGHT_ENERGY_MENAGMENT_SYSTEM_PROTO_LIGHT_ENERGY_MENAGMENT_SYSTEM_PB_H_INCLUDED
#define PB_LIGHT_ENERGY_MENAGMENT_SYSTEM_PROTO_LIGHT_ENERGY_MENAGMENT_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _light_energy_menagment_system_Device { 
    pb_callback_t name;
    pb_callback_t mac;
} light_energy_menagment_system_Device;

typedef struct _light_energy_menagment_system_LampData { 
    uint32_t timestamp; 
    float illuminance; 
    float voltage; 
    float current; 
    float power; 
    float energy; 
    float frequency; 
    float power_factor; 
} light_energy_menagment_system_LampData;

typedef struct _light_energy_menagment_system_DataPacket { 
    bool has_device;
    light_energy_menagment_system_Device device; 
    bool has_lamp_data;
    light_energy_menagment_system_LampData lamp_data; 
} light_energy_menagment_system_DataPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define light_energy_menagment_system_Device_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define light_energy_menagment_system_LampData_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define light_energy_menagment_system_DataPacket_init_default {false, light_energy_menagment_system_Device_init_default, false, light_energy_menagment_system_LampData_init_default}
#define light_energy_menagment_system_Device_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define light_energy_menagment_system_LampData_init_zero {0, 0, 0, 0, 0, 0, 0, 0}
#define light_energy_menagment_system_DataPacket_init_zero {false, light_energy_menagment_system_Device_init_zero, false, light_energy_menagment_system_LampData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define light_energy_menagment_system_Device_name_tag 1
#define light_energy_menagment_system_Device_mac_tag 2
#define light_energy_menagment_system_LampData_timestamp_tag 3
#define light_energy_menagment_system_LampData_illuminance_tag 4
#define light_energy_menagment_system_LampData_voltage_tag 5
#define light_energy_menagment_system_LampData_current_tag 6
#define light_energy_menagment_system_LampData_power_tag 7
#define light_energy_menagment_system_LampData_energy_tag 8
#define light_energy_menagment_system_LampData_frequency_tag 9
#define light_energy_menagment_system_LampData_power_factor_tag 10
#define light_energy_menagment_system_DataPacket_device_tag 11
#define light_energy_menagment_system_DataPacket_lamp_data_tag 12

/* Struct field encoding specification for nanopb */
#define light_energy_menagment_system_Device_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   mac,               2)
#define light_energy_menagment_system_Device_CALLBACK pb_default_field_callback
#define light_energy_menagment_system_Device_DEFAULT NULL

#define light_energy_menagment_system_LampData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    illuminance,       4) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    power,             7) \
X(a, STATIC,   SINGULAR, FLOAT,    energy,            8) \
X(a, STATIC,   SINGULAR, FLOAT,    frequency,         9) \
X(a, STATIC,   SINGULAR, FLOAT,    power_factor,     10)
#define light_energy_menagment_system_LampData_CALLBACK NULL
#define light_energy_menagment_system_LampData_DEFAULT NULL

#define light_energy_menagment_system_DataPacket_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,           11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lamp_data,        12)
#define light_energy_menagment_system_DataPacket_CALLBACK NULL
#define light_energy_menagment_system_DataPacket_DEFAULT NULL
#define light_energy_menagment_system_DataPacket_device_MSGTYPE light_energy_menagment_system_Device
#define light_energy_menagment_system_DataPacket_lamp_data_MSGTYPE light_energy_menagment_system_LampData

extern const pb_msgdesc_t light_energy_menagment_system_Device_msg;
extern const pb_msgdesc_t light_energy_menagment_system_LampData_msg;
extern const pb_msgdesc_t light_energy_menagment_system_DataPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define light_energy_menagment_system_Device_fields &light_energy_menagment_system_Device_msg
#define light_energy_menagment_system_LampData_fields &light_energy_menagment_system_LampData_msg
#define light_energy_menagment_system_DataPacket_fields &light_energy_menagment_system_DataPacket_msg

/* Maximum encoded size of messages (where known) */
/* light_energy_menagment_system_Device_size depends on runtime parameters */
/* light_energy_menagment_system_DataPacket_size depends on runtime parameters */
#define light_energy_menagment_system_LampData_size 41

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
