/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_LIGHT_ENERGY_MANAGEMENT_SYSTEM_PROTO_LIGHT_ENERGY_MANAGEMENT_SYSTEM_PB_H_INCLUDED
#define PB_LIGHT_ENERGY_MANAGEMENT_SYSTEM_PROTO_LIGHT_ENERGY_MANAGEMENT_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _light_energy_management_system_DeviceType { 
    light_energy_management_system_DeviceType_LampController = 0 
} light_energy_management_system_DeviceType;

typedef enum _light_energy_management_system_MeasurementType { 
    light_energy_management_system_MeasurementType_Illuminance = 0, 
    light_energy_management_system_MeasurementType_Voltage = 1, 
    light_energy_management_system_MeasurementType_Current = 2, 
    light_energy_management_system_MeasurementType_Power = 3, 
    light_energy_management_system_MeasurementType_Energy = 4, 
    light_energy_management_system_MeasurementType_Frequency = 5, 
    light_energy_management_system_MeasurementType_PowerFactor = 6 
} light_energy_management_system_MeasurementType;

/* Struct definitions */
typedef struct _light_energy_management_system_Device { 
    pb_callback_t name; 
    pb_callback_t mac; 
    light_energy_management_system_DeviceType type; 
} light_energy_management_system_Device;

typedef struct _light_energy_management_system_DeviceMeasurments { 
    uint32_t timestamp; 
    pb_callback_t measurements; 
} light_energy_management_system_DeviceMeasurments;

typedef struct _light_energy_management_system_Measurement { 
    float value; 
    light_energy_management_system_MeasurementType type; 
} light_energy_management_system_Measurement;

typedef struct _light_energy_management_system_DataPacket { 
    bool has_device;
    light_energy_management_system_Device device; 
    pb_callback_t device_measurements; 
} light_energy_management_system_DataPacket;


/* Helper constants for enums */
#define _light_energy_management_system_DeviceType_MIN light_energy_management_system_DeviceType_LampController
#define _light_energy_management_system_DeviceType_MAX light_energy_management_system_DeviceType_LampController
#define _light_energy_management_system_DeviceType_ARRAYSIZE ((light_energy_management_system_DeviceType)(light_energy_management_system_DeviceType_LampController+1))

#define _light_energy_management_system_MeasurementType_MIN light_energy_management_system_MeasurementType_Illuminance
#define _light_energy_management_system_MeasurementType_MAX light_energy_management_system_MeasurementType_PowerFactor
#define _light_energy_management_system_MeasurementType_ARRAYSIZE ((light_energy_management_system_MeasurementType)(light_energy_management_system_MeasurementType_PowerFactor+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define light_energy_management_system_Device_init_default {{{NULL}, NULL}, {{NULL}, NULL}, _light_energy_management_system_DeviceType_MIN}
#define light_energy_management_system_Measurement_init_default {0, _light_energy_management_system_MeasurementType_MIN}
#define light_energy_management_system_DeviceMeasurments_init_default {0, {{NULL}, NULL}}
#define light_energy_management_system_DataPacket_init_default {false, light_energy_management_system_Device_init_default, {{NULL}, NULL}}
#define light_energy_management_system_Device_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, _light_energy_management_system_DeviceType_MIN}
#define light_energy_management_system_Measurement_init_zero {0, _light_energy_management_system_MeasurementType_MIN}
#define light_energy_management_system_DeviceMeasurments_init_zero {0, {{NULL}, NULL}}
#define light_energy_management_system_DataPacket_init_zero {false, light_energy_management_system_Device_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define light_energy_management_system_Device_name_tag 1
#define light_energy_management_system_Device_mac_tag 2
#define light_energy_management_system_Device_type_tag 3
#define light_energy_management_system_DeviceMeasurments_timestamp_tag 1
#define light_energy_management_system_DeviceMeasurments_measurements_tag 2
#define light_energy_management_system_Measurement_value_tag 1
#define light_energy_management_system_Measurement_type_tag 2
#define light_energy_management_system_DataPacket_device_tag 1
#define light_energy_management_system_DataPacket_device_measurements_tag 2

/* Struct field encoding specification for nanopb */
#define light_energy_management_system_Device_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   mac,               2) \
X(a, STATIC,   SINGULAR, UENUM,    type,              3)
#define light_energy_management_system_Device_CALLBACK pb_default_field_callback
#define light_energy_management_system_Device_DEFAULT NULL

#define light_energy_management_system_Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2)
#define light_energy_management_system_Measurement_CALLBACK NULL
#define light_energy_management_system_Measurement_DEFAULT NULL

#define light_energy_management_system_DeviceMeasurments_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  measurements,      2)
#define light_energy_management_system_DeviceMeasurments_CALLBACK pb_default_field_callback
#define light_energy_management_system_DeviceMeasurments_DEFAULT NULL
#define light_energy_management_system_DeviceMeasurments_measurements_MSGTYPE light_energy_management_system_Measurement

#define light_energy_management_system_DataPacket_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  device_measurements,   2)
#define light_energy_management_system_DataPacket_CALLBACK pb_default_field_callback
#define light_energy_management_system_DataPacket_DEFAULT NULL
#define light_energy_management_system_DataPacket_device_MSGTYPE light_energy_management_system_Device
#define light_energy_management_system_DataPacket_device_measurements_MSGTYPE light_energy_management_system_DeviceMeasurments

extern const pb_msgdesc_t light_energy_management_system_Device_msg;
extern const pb_msgdesc_t light_energy_management_system_Measurement_msg;
extern const pb_msgdesc_t light_energy_management_system_DeviceMeasurments_msg;
extern const pb_msgdesc_t light_energy_management_system_DataPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define light_energy_management_system_Device_fields &light_energy_management_system_Device_msg
#define light_energy_management_system_Measurement_fields &light_energy_management_system_Measurement_msg
#define light_energy_management_system_DeviceMeasurments_fields &light_energy_management_system_DeviceMeasurments_msg
#define light_energy_management_system_DataPacket_fields &light_energy_management_system_DataPacket_msg

/* Maximum encoded size of messages (where known) */
/* light_energy_management_system_Device_size depends on runtime parameters */
/* light_energy_management_system_DeviceMeasurments_size depends on runtime parameters */
/* light_energy_management_system_DataPacket_size depends on runtime parameters */
#define light_energy_management_system_Measurement_size 7

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
