targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/proto/**
    builders:
      protoc_builder:
        options:
          protobuf_version: "3.19.1"
          protoc_plugin_version: "20.0.0"
          root_dir: "lib/proto/"
          proto_paths:
            - "lib/proto/"
          out_dir: "lib/proto"
